import { VideoProvider, ProviderStrength } from '@shared/types/video-providers';

export const VIDEO_PROVIDERS: Record<string, VideoProvider> = {
  
  'kling-1.6': {
    id: 'kling-1.6',
    name: 'Kling 1.6',
    version: '1.6',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 10,
      strengths: ['human-faces', 'human-motion', 'nature-scenes'],
      weaknesses: ['specific-actions', 'text-in-video', 'fine-details'],
      motionQuality: 'good',
      temporalConsistency: 'medium',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.30,
    apiProvider: 'piapi',
    modelId: 'kling-v1.6',
  },
  
  'kling-2.0': {
    id: 'kling-2.0',
    name: 'Kling 2.0',
    version: '2.0',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 10,
      strengths: ['human-faces', 'human-motion', 'cinematic', 'camera-movement'],
      weaknesses: ['specific-actions', 'text-in-video'],
      motionQuality: 'excellent',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.35,
    apiProvider: 'piapi',
    modelId: 'kling-v2',
  },
  
  'kling-2.1': {
    id: 'kling-2.1',
    name: 'Kling 2.1',
    version: '2.1',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 10,
      strengths: ['human-faces', 'human-motion', 'cinematic', 'product-shots'],
      weaknesses: ['specific-actions', 'text-in-video'],
      motionQuality: 'excellent',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.40,
    apiProvider: 'piapi',
    modelId: 'kling-v2.1',
  },
  
  'kling-2.5-turbo': {
    id: 'kling-2.5-turbo',
    name: 'Kling 2.5 Turbo',
    version: '2.5',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 10,
      strengths: ['human-faces', 'human-motion', 'cinematic', 'product-shots', 'camera-movement'],
      weaknesses: ['text-in-video'],
      motionQuality: 'excellent',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.45,
    apiProvider: 'piapi',
    modelId: 'kling-v2.5-turbo',
  },
  
  'kling-effects': {
    id: 'kling-effects',
    name: 'Kling Effects',
    version: '1.0',
    capabilities: {
      imageToVideo: true,
      textToVideo: false,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 5,
      strengths: ['stylized', 'animated'],
      weaknesses: ['specific-actions', 'cinematic' as any],
      motionQuality: 'good',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: ['squish', 'rocket', 'heart', 'inflate', 'melt', 'explode', 'levitate'],
    },
    costPer10Seconds: 0.25,
    apiProvider: 'piapi',
    modelId: 'kling-effects',
  },
  
  'kling-avatar': {
    id: 'kling-avatar',
    name: 'Kling AI Avatar',
    version: '1.0',
    capabilities: {
      imageToVideo: true,
      textToVideo: false,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 48,
      maxDuration: 60,
      strengths: ['talking-heads', 'human-faces'],
      weaknesses: ['specific-actions' as any, 'complex-motion'],
      motionQuality: 'excellent',
      temporalConsistency: 'high',
      nativeAudio: true,
      lipSync: true,
      effectsPresets: [],
    },
    costPer10Seconds: 0.50,
    apiProvider: 'piapi',
    modelId: 'kling-avatar',
  },
  
  'wan-2.1': {
    id: 'wan-2.1',
    name: 'Wan 2.1',
    version: '2.1',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: true,
      maxResolution: '720p',
      maxFps: 30,
      maxDuration: 5,
      strengths: ['stylized', 'animated', 'fast-motion'],
      weaknesses: ['fine-details' as any],
      motionQuality: 'good',
      temporalConsistency: 'medium',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.15,
    apiProvider: 'piapi',
    modelId: 'wan-2.1',
  },
  
  'wan-2.6': {
    id: 'wan-2.6',
    name: 'Wan 2.6',
    version: '2.6',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: true,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 8,
      strengths: ['stylized', 'animated', 'fast-motion', 'camera-movement'],
      weaknesses: ['fine-details', 'translucent-materials'],
      motionQuality: 'good',
      temporalConsistency: 'medium',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.20,
    apiProvider: 'piapi',
    modelId: 'wan-2.6',
  },
  
  'veo-2': {
    id: 'veo-2',
    name: 'Veo 2',
    version: '2.0',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 8,
      strengths: ['cinematic', 'nature-scenes', 'camera-movement'],
      weaknesses: ['text-in-video', 'specific-actions'],
      motionQuality: 'excellent',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.50,
    apiProvider: 'piapi',
    modelId: 'veo-2',
  },
  
  'veo-3.1': {
    id: 'veo-3.1',
    name: 'Veo 3.1 Quality',
    version: '3.1',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '4k',
      maxFps: 30,
      maxDuration: 10,
      strengths: ['cinematic', 'nature-scenes', 'camera-movement', 'product-shots'],
      weaknesses: ['text-in-video'],
      motionQuality: 'cinematic',
      temporalConsistency: 'high',
      nativeAudio: true,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.75,
    apiProvider: 'piapi',
    modelId: 'veo-3.1-quality',
  },
  
  'seedance-1.0': {
    id: 'seedance-1.0',
    name: 'Seedance 1.0',
    version: '1.0',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '720p',
      maxFps: 30,
      maxDuration: 5,
      strengths: ['stylized', 'animated', 'human-motion'],
      weaknesses: ['fine-details'],
      motionQuality: 'good',
      temporalConsistency: 'medium',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.20,
    apiProvider: 'piapi',
    modelId: 'seedance-1.0',
  },
  
  'hailuo-minimax': {
    id: 'hailuo-minimax',
    name: 'Hailuo MiniMax',
    version: '1.0',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 6,
      strengths: ['b-roll', 'nature-scenes', 'fast-motion'],
      weaknesses: ['specific-actions', 'fine-details'],
      motionQuality: 'good',
      temporalConsistency: 'medium',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.15,
    apiProvider: 'piapi',
    modelId: 'hailuo-minimax',
  },
  
  'runway-gen3': {
    id: 'runway-gen3',
    name: 'Runway Gen-3 Alpha',
    version: '3.0',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 10,
      strengths: ['cinematic', 'camera-movement', 'human-faces'],
      weaknesses: ['text-in-video', 'specific-actions'],
      motionQuality: 'excellent',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.60,
    apiProvider: 'runway',
    modelId: 'gen3-alpha',
  },
  
  'luma-dream-machine': {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    version: '1.0',
    capabilities: {
      imageToVideo: true,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '1080p',
      maxFps: 30,
      maxDuration: 5,
      strengths: ['product-shots', 'slow-motion', 'nature-scenes'],
      weaknesses: ['specific-actions', 'fast-motion'],
      motionQuality: 'excellent',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.40,
    apiProvider: 'piapi',
    modelId: 'luma-dream-machine',
  },
  
  'flux-1-dev': {
    id: 'flux-1-dev',
    name: 'Flux.1 Dev',
    version: '1.0',
    capabilities: {
      imageToVideo: false,
      textToVideo: false,
      imageToImage: true,
      maxResolution: '1080p',
      maxFps: 0,
      maxDuration: 0,
      strengths: ['product-shots', 'food-content', 'fine-details' as any],
      weaknesses: [],
      motionQuality: 'basic',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.05,
    apiProvider: 'piapi',
    modelId: 'flux-1-dev',
  },
  
  'stable-diffusion-3': {
    id: 'stable-diffusion-3',
    name: 'Stable Diffusion 3',
    version: '3.0',
    capabilities: {
      imageToVideo: false,
      textToVideo: false,
      imageToImage: true,
      maxResolution: '1080p',
      maxFps: 0,
      maxDuration: 0,
      strengths: ['stylized', 'animated', 'text-rendering'],
      weaknesses: ['fine-details'],
      motionQuality: 'basic',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: [],
    },
    costPer10Seconds: 0.03,
    apiProvider: 'piapi',
    modelId: 'sd3',
  },
  
  'remotion-motion-graphics': {
    id: 'remotion-motion-graphics',
    name: 'Remotion Motion Graphics',
    version: '1.0',
    capabilities: {
      imageToVideo: false,
      textToVideo: true,
      imageToImage: false,
      maxResolution: '4k',
      maxFps: 60,
      maxDuration: 300,
      strengths: ['text-rendering', 'animated', 'stylized'],
      weaknesses: [],
      motionQuality: 'excellent',
      temporalConsistency: 'high',
      nativeAudio: false,
      lipSync: false,
      effectsPresets: ['kinetic-text', 'infographic', 'split-screen', 'before-after', 'counter', 'progress-bar'],
    },
    costPer10Seconds: 0.00,
    apiProvider: 'remotion',
    modelId: 'motion-graphics-engine',
  },
};

export function getProvidersByCapability(
  capability: 'imageToVideo' | 'textToVideo' | 'imageToImage'
): VideoProvider[] {
  return Object.values(VIDEO_PROVIDERS).filter(p => p.capabilities[capability]);
}

export function getProvidersByStrength(strength: ProviderStrength): VideoProvider[] {
  return Object.values(VIDEO_PROVIDERS).filter(p => 
    p.capabilities.strengths.includes(strength)
  );
}

export function getProviderById(id: string): VideoProvider | undefined {
  return VIDEO_PROVIDERS[id];
}

export function getAllVideoProviders(): VideoProvider[] {
  return Object.values(VIDEO_PROVIDERS).filter(
    p => p.capabilities.textToVideo || p.capabilities.imageToVideo
  );
}

export function getProviderCost(providerId: string, durationSeconds: number): number {
  const provider = VIDEO_PROVIDERS[providerId];
  if (!provider) return 0;
  return (durationSeconds / 10) * provider.costPer10Seconds;
}
