export interface AssetTypeRequirements {
  recommendedFormat: string[];
  transparentBackground: boolean | 'optional' | 'recommended';
  minResolution: { width: number; height: number } | null;
  aspectRatio: string;
  tileable?: 'optional';
  maxDuration?: number;
}

export interface PlacementRules {
  canBeComposited: boolean;
  canBeAnimated: boolean;
  typicalPosition: string;
  typicalScale: string;
  typicalOpacity?: number;
  animationStyle?: string;
  backgroundRequirement?: 'dark' | 'light';
}

export interface PersonMetadata {
  requiresName?: boolean | 'optional';
  requiresTitle?: boolean | 'optional';
  requiresCredentials?: boolean;
  requiresConsent?: boolean;
  requiresTestimonialRelease?: boolean;
  requiresMedicalDisclaimer?: boolean;
  requiresEndorsementDisclosure?: boolean;
}

export interface AssetType {
  id: string;
  category: string;
  label: string;
  description: string;
  icon: string;
  examples: string[];
  usageContext: string[];
  requirements: AssetTypeRequirements;
  promptKeywords: string[];
  placementRules: PlacementRules;
  personMetadata?: PersonMetadata;
}

export interface AssetCategory {
  id: string;
  label: string;
  icon: string;
  description: string;
}

export const PRODUCT_ASSET_TYPES: Record<string, AssetType> = {
  'product-hero-single': {
    id: 'product-hero-single',
    category: 'products',
    label: 'Product Hero (Single)',
    description: 'Single product on clean/transparent background for feature placement',
    icon: 'Package',
    examples: ['Single supplement bottle on white', 'One lotion tube, no background'],
    usageContext: ['product-shot', 'hero', 'composition'],
    requirements: {
      recommendedFormat: ['png', 'webp'],
      transparentBackground: 'recommended',
      minResolution: { width: 1000, height: 1000 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['product', 'bottle', 'supplement', 'item', 'package'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'large',
    },
  },
  'product-hero-group': {
    id: 'product-hero-group',
    category: 'products',
    label: 'Product Group/Lineup',
    description: 'Multiple products arranged together for overview shots',
    icon: 'Layers',
    examples: ['Full product line on display', '3 bottles arranged together'],
    usageContext: ['product-overview', 'lineup', 'collection'],
    requirements: {
      recommendedFormat: ['png', 'jpg', 'webp'],
      transparentBackground: 'optional',
      minResolution: { width: 1500, height: 1000 },
      aspectRatio: 'landscape-preferred',
    },
    promptKeywords: ['products', 'lineup', 'collection', 'range', 'family'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium-large',
    },
  },
  'product-lifestyle': {
    id: 'product-lifestyle',
    category: 'products',
    label: 'Product Lifestyle Shot',
    description: 'Product shown in real-world context or being used',
    icon: 'Heart',
    examples: ['Lotion on bathroom counter', 'Supplements next to breakfast'],
    usageContext: ['lifestyle', 'context', 'in-use'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['lifestyle', 'using', 'daily routine', 'natural setting'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'product-packaging-front': {
    id: 'product-packaging-front',
    category: 'products',
    label: 'Packaging (Front Label)',
    description: 'Front-facing product label, clearly readable',
    icon: 'Tag',
    examples: ['Bottle front label', 'Box front panel'],
    usageContext: ['detail', 'label', 'ingredients'],
    requirements: {
      recommendedFormat: ['png', 'jpg'],
      transparentBackground: 'optional',
      minResolution: { width: 1200, height: 1200 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['label', 'packaging', 'front', 'details'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'large',
    },
  },
  'product-packaging-back': {
    id: 'product-packaging-back',
    category: 'products',
    label: 'Packaging (Back/Ingredients)',
    description: 'Back label showing ingredients, directions, or details',
    icon: 'FileText',
    examples: ['Supplement facts panel', 'Ingredient list', 'Usage directions'],
    usageContext: ['ingredients', 'details', 'transparency'],
    requirements: {
      recommendedFormat: ['png', 'jpg'],
      transparentBackground: false,
      minResolution: { width: 1200, height: 1500 },
      aspectRatio: 'portrait-preferred',
    },
    promptKeywords: ['ingredients', 'supplement facts', 'directions', 'back label'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'large',
    },
  },
  'product-ingredient-raw': {
    id: 'product-ingredient-raw',
    category: 'products',
    label: 'Raw Ingredient',
    description: 'Photo of actual ingredient (herb, extract, etc.)',
    icon: 'Leaf',
    examples: ['Black cohosh plant', 'Lavender sprigs', 'Honey in jar'],
    usageContext: ['ingredient-showcase', 'natural', 'sourcing'],
    requirements: {
      recommendedFormat: ['png', 'jpg', 'webp'],
      transparentBackground: 'recommended',
      minResolution: { width: 800, height: 800 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['ingredient', 'natural', 'herb', 'plant', 'extract', 'source'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'flexible',
      typicalScale: 'medium',
    },
  },
  'product-size-comparison': {
    id: 'product-size-comparison',
    category: 'products',
    label: 'Size Comparison',
    description: 'Product shown with reference object for scale',
    icon: 'Ruler',
    examples: ['Bottle next to hand', 'Product next to coin'],
    usageContext: ['scale', 'size', 'comparison'],
    requirements: {
      recommendedFormat: ['jpg', 'png'],
      transparentBackground: false,
      minResolution: { width: 1200, height: 1200 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['size', 'scale', 'how big', 'comparison'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium-large',
    },
  },
  'product-bundle-kit': {
    id: 'product-bundle-kit',
    category: 'products',
    label: 'Bundle/Kit',
    description: 'Gift set, starter kit, or bundled products',
    icon: 'Gift',
    examples: ['Wellness starter kit', 'Gift box set', 'Travel bundle'],
    usageContext: ['bundle', 'gift', 'kit', 'set'],
    requirements: {
      recommendedFormat: ['png', 'jpg'],
      transparentBackground: 'optional',
      minResolution: { width: 1500, height: 1000 },
      aspectRatio: 'landscape-preferred',
    },
    promptKeywords: ['bundle', 'kit', 'set', 'gift', 'collection'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'large',
    },
  },
};

export const LOCATION_ASSET_TYPES: Record<string, AssetType> = {
  'location-exterior-sign': {
    id: 'location-exterior-sign',
    category: 'location',
    label: 'Exterior Building Sign',
    description: 'Outdoor signage, storefront, or building identification',
    icon: 'Building',
    examples: ['Pine Hill Farm entrance sign', 'Storefront with logo'],
    usageContext: ['establishing-shot', 'intro', 'location'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['sign', 'building', 'exterior', 'storefront', 'entrance', 'facility'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'location-exterior-building': {
    id: 'location-exterior-building',
    category: 'location',
    label: 'Exterior Building Shot',
    description: 'Full building exterior without focus on signage',
    icon: 'Home',
    examples: ['Facility from parking lot', 'Building aerial view'],
    usageContext: ['establishing-shot', 'overview', 'facility'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['building', 'facility', 'headquarters', 'location', 'premises'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'location-interior-workspace': {
    id: 'location-interior-workspace',
    category: 'location',
    label: 'Interior Workspace',
    description: 'Office, lab, or work area inside facility',
    icon: 'Briefcase',
    examples: ['Lab where products are made', 'Office space', 'Quality control area'],
    usageContext: ['behind-the-scenes', 'process', 'facility-tour'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['inside', 'facility', 'lab', 'workspace', 'behind the scenes', 'living room', 'room', 'interior', 'home', 'cozy', 'indoor', 'house', 'kitchen', 'sunlit'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'location-interior-retail': {
    id: 'location-interior-retail',
    category: 'location',
    label: 'Interior Retail/Display',
    description: 'Showroom, retail space, or product display area',
    icon: 'Store',
    examples: ['Product showroom', 'Retail display', 'Customer-facing area'],
    usageContext: ['retail', 'display', 'shopping'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['store', 'showroom', 'display', 'retail', 'shop'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'location-farm-grounds': {
    id: 'location-farm-grounds',
    category: 'location',
    label: 'Farm/Outdoor Grounds',
    description: 'Outdoor property, farm land, gardens, or natural areas',
    icon: 'Trees',
    examples: ['Herb garden', 'Farm fields', 'Natural surroundings'],
    usageContext: ['nature', 'sourcing', 'organic', 'natural'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['farm', 'garden', 'outdoor', 'nature', 'field', 'organic', 'grounds'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'location-manufacturing': {
    id: 'location-manufacturing',
    category: 'location',
    label: 'Manufacturing/Production',
    description: 'Production line, manufacturing equipment, or processing area',
    icon: 'Factory',
    examples: ['Bottling line', 'Mixing equipment', 'Packaging station'],
    usageContext: ['process', 'manufacturing', 'quality'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['manufacturing', 'production', 'making', 'process', 'equipment'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'location-warehouse': {
    id: 'location-warehouse',
    category: 'location',
    label: 'Warehouse/Storage',
    description: 'Storage facility, inventory, or shipping area',
    icon: 'Warehouse',
    examples: ['Product warehouse', 'Shipping department', 'Inventory shelves'],
    usageContext: ['operations', 'scale', 'fulfillment'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['warehouse', 'storage', 'inventory', 'shipping', 'fulfillment'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
};

export const PEOPLE_ASSET_TYPES: Record<string, AssetType> = {
  'people-founder-portrait': {
    id: 'people-founder-portrait',
    category: 'people',
    label: 'Founder/Owner Portrait',
    description: 'Professional portrait of company founder or owner',
    icon: 'Crown',
    examples: ['CEO headshot', 'Founder professional photo'],
    usageContext: ['authority', 'story', 'leadership', 'about-us'],
    requirements: {
      recommendedFormat: ['jpg', 'png'],
      transparentBackground: 'optional',
      minResolution: { width: 800, height: 1000 },
      aspectRatio: 'portrait-preferred',
    },
    promptKeywords: ['founder', 'owner', 'CEO', 'leadership', 'started by'],
    personMetadata: {
      requiresName: true,
      requiresTitle: true,
      requiresConsent: true,
    },
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center-left',
      typicalScale: 'medium-large',
    },
  },
  'people-executive-portrait': {
    id: 'people-executive-portrait',
    category: 'people',
    label: 'Executive/Leadership Portrait',
    description: 'Professional portrait of executive team member',
    icon: 'UserCheck',
    examples: ['VP headshot', 'Director portrait', 'Management team member'],
    usageContext: ['leadership', 'team', 'about-us'],
    requirements: {
      recommendedFormat: ['jpg', 'png'],
      transparentBackground: 'optional',
      minResolution: { width: 800, height: 1000 },
      aspectRatio: 'portrait-preferred',
    },
    promptKeywords: ['executive', 'leadership', 'director', 'VP', 'management'],
    personMetadata: {
      requiresName: true,
      requiresTitle: true,
      requiresConsent: true,
    },
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium',
    },
  },
  'people-employee-headshot': {
    id: 'people-employee-headshot',
    category: 'people',
    label: 'Employee Headshot',
    description: 'Professional portrait of staff member',
    icon: 'User',
    examples: ['Team member photo', 'Staff headshot'],
    usageContext: ['team', 'testimonial', 'about-us'],
    requirements: {
      recommendedFormat: ['jpg', 'png'],
      transparentBackground: 'optional',
      minResolution: { width: 600, height: 800 },
      aspectRatio: 'portrait-preferred',
    },
    promptKeywords: ['employee', 'team member', 'staff', 'our team'],
    personMetadata: {
      requiresName: true,
      requiresTitle: 'optional',
      requiresConsent: true,
    },
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium',
    },
  },
  'people-employee-action': {
    id: 'people-employee-action',
    category: 'people',
    label: 'Employee at Work',
    description: 'Staff member performing their job or in work context',
    icon: 'UserCog',
    examples: ['Lab tech working', 'Customer service helping', 'Packaging products'],
    usageContext: ['behind-the-scenes', 'process', 'culture'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['working', 'making', 'team at work', 'behind the scenes'],
    personMetadata: {
      requiresName: 'optional',
      requiresTitle: 'optional',
      requiresConsent: true,
    },
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'people-expert-portrait': {
    id: 'people-expert-portrait',
    category: 'people',
    label: 'Expert/Specialist Portrait',
    description: 'Photo of credentialed expert (doctor, nutritionist, etc.)',
    icon: 'GraduationCap',
    examples: ['Staff nutritionist', 'Medical advisor', 'Formulation scientist'],
    usageContext: ['authority', 'expertise', 'credibility'],
    requirements: {
      recommendedFormat: ['jpg', 'png'],
      transparentBackground: 'optional',
      minResolution: { width: 800, height: 1000 },
      aspectRatio: 'portrait-preferred',
    },
    promptKeywords: ['expert', 'doctor', 'specialist', 'scientist', 'nutritionist', 'formulated by'],
    personMetadata: {
      requiresName: true,
      requiresTitle: true,
      requiresCredentials: true,
      requiresConsent: true,
    },
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium-large',
    },
  },
  'people-customer-portrait': {
    id: 'people-customer-portrait',
    category: 'people',
    label: 'Customer Portrait',
    description: 'Real customer photo (with permission) for testimonials',
    icon: 'Heart',
    examples: ['Happy customer photo', 'Testimonial portrait'],
    usageContext: ['testimonial', 'social-proof', 'reviews'],
    requirements: {
      recommendedFormat: ['jpg', 'png'],
      transparentBackground: 'optional',
      minResolution: { width: 600, height: 800 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['customer', 'testimonial', 'review', 'real people', 'results'],
    personMetadata: {
      requiresName: 'optional',
      requiresConsent: true,
      requiresTestimonialRelease: true,
    },
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium',
    },
  },
  'people-customer-beforeafter': {
    id: 'people-customer-beforeafter',
    category: 'people',
    label: 'Customer Before/After',
    description: 'Before and after photos showing results (with permission)',
    icon: 'ArrowRightLeft',
    examples: ['Skin improvement', 'Wellness transformation'],
    usageContext: ['results', 'transformation', 'proof'],
    requirements: {
      recommendedFormat: ['jpg', 'png'],
      transparentBackground: false,
      minResolution: { width: 1200, height: 800 },
      aspectRatio: 'landscape-preferred',
    },
    promptKeywords: ['before', 'after', 'results', 'transformation', 'improvement'],
    personMetadata: {
      requiresConsent: true,
      requiresTestimonialRelease: true,
      requiresMedicalDisclaimer: true,
    },
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'people-group-team': {
    id: 'people-group-team',
    category: 'people',
    label: 'Team Group Photo',
    description: 'Multiple team members together',
    icon: 'Users',
    examples: ['Full team photo', 'Department group shot'],
    usageContext: ['about-us', 'culture', 'team'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: 'landscape-preferred',
    },
    promptKeywords: ['team', 'group', 'our people', 'staff'],
    personMetadata: {
      requiresConsent: true,
    },
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'people-spokesperson': {
    id: 'people-spokesperson',
    category: 'people',
    label: 'Brand Spokesperson',
    description: 'Official brand representative or ambassador',
    icon: 'Mic',
    examples: ['Brand ambassador', 'Paid spokesperson', 'Influencer partner'],
    usageContext: ['promotion', 'endorsement', 'campaign'],
    requirements: {
      recommendedFormat: ['jpg', 'png'],
      transparentBackground: 'optional',
      minResolution: { width: 1000, height: 1200 },
      aspectRatio: 'portrait-preferred',
    },
    promptKeywords: ['spokesperson', 'ambassador', 'endorsement', 'partner'],
    personMetadata: {
      requiresName: true,
      requiresConsent: true,
      requiresEndorsementDisclosure: true,
    },
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'large',
    },
  },
};

export const LOGO_ASSET_TYPES: Record<string, AssetType> = {
  'logo-primary-color': {
    id: 'logo-primary-color',
    category: 'logos',
    label: 'Primary Logo (Full Color)',
    description: 'Main brand logo in full color, for hero placement',
    icon: 'Hexagon',
    examples: ['Pine Hill Farm main logo', 'Full color brand mark'],
    usageContext: ['hero', 'intro', 'outro', 'prominent'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 1000, height: 500 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['logo', 'brand', 'Pine Hill Farm'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'large',
      animationStyle: 'scale-up',
    },
  },
  'logo-primary-white': {
    id: 'logo-primary-white',
    category: 'logos',
    label: 'Primary Logo (White/Light)',
    description: 'Main logo in white/light color for dark backgrounds',
    icon: 'Hexagon',
    examples: ['White version of logo', 'Reversed logo'],
    usageContext: ['dark-background', 'overlay', 'cinematic'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 1000, height: 500 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['logo', 'brand'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'large',
      backgroundRequirement: 'dark',
    },
  },
  'logo-primary-dark': {
    id: 'logo-primary-dark',
    category: 'logos',
    label: 'Primary Logo (Dark/Black)',
    description: 'Main logo in dark/black color for light backgrounds',
    icon: 'Hexagon',
    examples: ['Black version of logo', 'Dark single-color logo'],
    usageContext: ['light-background', 'print-style'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 1000, height: 500 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['logo', 'brand'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'large',
      backgroundRequirement: 'light',
    },
  },
  'logo-watermark': {
    id: 'logo-watermark',
    category: 'logos',
    label: 'Watermark Logo',
    description: 'Simplified logo for corner watermark placement',
    icon: 'Stamp',
    examples: ['Small corner logo', 'Simplified brand mark'],
    usageContext: ['watermark', 'corner', 'subtle-branding'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 200, height: 200 },
      aspectRatio: 'square-preferred',
    },
    promptKeywords: [],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom-right',
      typicalScale: 'small',
      typicalOpacity: 0.5,
      animationStyle: 'fade-in',
    },
  },
  'logo-icon-only': {
    id: 'logo-icon-only',
    category: 'logos',
    label: 'Logo Icon/Symbol Only',
    description: 'Just the icon/symbol portion without text',
    icon: 'Circle',
    examples: ['Brand symbol', 'App icon', 'Favicon-style mark'],
    usageContext: ['icon', 'small-space', 'social-media'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 500, height: 500 },
      aspectRatio: 'square',
    },
    promptKeywords: ['icon', 'symbol'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'flexible',
      typicalScale: 'small-medium',
    },
  },
  'logo-wordmark': {
    id: 'logo-wordmark',
    category: 'logos',
    label: 'Wordmark/Text Logo',
    description: 'Text-only version of logo without icon',
    icon: 'Type',
    examples: ['Brand name in logo font', 'Text-only logo'],
    usageContext: ['text-heavy', 'signature', 'formal'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 800, height: 200 },
      aspectRatio: 'wide',
    },
    promptKeywords: ['Pine Hill Farm', 'brand name'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center-bottom',
      typicalScale: 'medium',
    },
  },
  'logo-tagline': {
    id: 'logo-tagline',
    category: 'logos',
    label: 'Logo with Tagline',
    description: 'Logo including brand tagline/slogan',
    icon: 'Quote',
    examples: ['Logo + "Naturally Better"', 'Full brand lockup with tagline'],
    usageContext: ['intro', 'outro', 'formal'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 1200, height: 600 },
      aspectRatio: 'landscape',
    },
    promptKeywords: ['logo', 'tagline', 'slogan'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'large',
    },
  },
  'logo-animated': {
    id: 'logo-animated',
    category: 'logos',
    label: 'Animated Logo',
    description: 'Pre-animated logo (GIF, video, or Lottie)',
    icon: 'Play',
    examples: ['Logo reveal animation', 'Animated brand intro'],
    usageContext: ['intro', 'outro', 'transition'],
    requirements: {
      recommendedFormat: ['gif', 'mp4', 'webm', 'json'],
      transparentBackground: 'recommended',
      minResolution: { width: 1000, height: 500 },
      aspectRatio: 'flexible',
    },
    promptKeywords: [],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: false,
      typicalPosition: 'center',
      typicalScale: 'large',
    },
  },
};

export const TRUST_ASSET_TYPES: Record<string, AssetType> = {
  'trust-certification-usda': {
    id: 'trust-certification-usda',
    category: 'trust',
    label: 'USDA Organic Certification',
    description: 'Official USDA Organic seal',
    icon: 'ShieldCheck',
    examples: ['USDA Organic badge'],
    usageContext: ['certification', 'organic', 'compliance'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 300, height: 300 },
      aspectRatio: 'square',
    },
    promptKeywords: ['USDA', 'organic', 'certified', 'certification'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom-left',
      typicalScale: 'small',
      animationStyle: 'fade-in',
    },
  },
  'trust-certification-nongmo': {
    id: 'trust-certification-nongmo',
    category: 'trust',
    label: 'Non-GMO Certification',
    description: 'Non-GMO Project Verified or similar seal',
    icon: 'ShieldCheck',
    examples: ['Non-GMO Project Verified badge'],
    usageContext: ['certification', 'non-gmo', 'compliance'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 300, height: 300 },
      aspectRatio: 'square',
    },
    promptKeywords: ['non-GMO', 'GMO-free', 'certified'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom-left',
      typicalScale: 'small',
    },
  },
  'trust-certification-gmp': {
    id: 'trust-certification-gmp',
    category: 'trust',
    label: 'GMP Certified',
    description: 'Good Manufacturing Practice certification',
    icon: 'ShieldCheck',
    examples: ['GMP Certified badge', 'cGMP seal'],
    usageContext: ['quality', 'manufacturing', 'compliance'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 300, height: 300 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['GMP', 'certified', 'quality', 'manufacturing'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom-left',
      typicalScale: 'small',
    },
  },
  'trust-certification-thirdparty': {
    id: 'trust-certification-thirdparty',
    category: 'trust',
    label: 'Third-Party Tested Badge',
    description: 'Independent lab testing certification',
    icon: 'FlaskConical',
    examples: ['Third-party tested seal', 'Lab verified badge'],
    usageContext: ['testing', 'verification', 'purity'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 300, height: 300 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['tested', 'third-party', 'lab', 'verified', 'purity'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom-left',
      typicalScale: 'small',
    },
  },
  'trust-certification-vegan': {
    id: 'trust-certification-vegan',
    category: 'trust',
    label: 'Vegan/Cruelty-Free Certification',
    description: 'Vegan Society, Leaping Bunny, or similar',
    icon: 'Leaf',
    examples: ['Vegan certified badge', 'Cruelty-free seal'],
    usageContext: ['vegan', 'cruelty-free', 'ethical'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 300, height: 300 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['vegan', 'cruelty-free', 'animal-free'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom-left',
      typicalScale: 'small',
    },
  },
  'trust-certification-other': {
    id: 'trust-certification-other',
    category: 'trust',
    label: 'Other Certification',
    description: 'Any other industry certification or seal',
    icon: 'Award',
    examples: ['Gluten-free certified', 'Kosher', 'Halal', 'B-Corp'],
    usageContext: ['certification', 'compliance'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 300, height: 300 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['certified', 'certification'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom-left',
      typicalScale: 'small',
    },
  },
  'trust-award-badge': {
    id: 'trust-award-badge',
    category: 'trust',
    label: 'Award/Recognition Badge',
    description: 'Industry award, "Best of" recognition, etc.',
    icon: 'Trophy',
    examples: ['Best of 2024 winner', "Editor's Choice", 'Industry award'],
    usageContext: ['awards', 'recognition', 'credibility'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 400, height: 400 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['award', 'winner', 'best', 'recognition'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'top-right',
      typicalScale: 'small-medium',
    },
  },
  'trust-partnership-logo': {
    id: 'trust-partnership-logo',
    category: 'trust',
    label: 'Partner Organization Logo',
    description: 'Logo of partner, affiliate, or collaborating organization',
    icon: 'Handshake',
    examples: ['Charity partner logo', 'Industry association', 'Retailer logo'],
    usageContext: ['partnership', 'collaboration', 'distribution'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 400, height: 200 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['partner', 'partnership', 'collaboration', 'available at'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom',
      typicalScale: 'small',
    },
  },
  'trust-press-logo': {
    id: 'trust-press-logo',
    category: 'trust',
    label: 'Press/Media Logo',
    description: 'Logo of media outlet that featured the brand',
    icon: 'Newspaper',
    examples: ['As seen in Forbes', 'Featured on GMA', 'NYT mention'],
    usageContext: ['press', 'media', 'as-seen-in'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 300, height: 100 },
      aspectRatio: 'landscape',
    },
    promptKeywords: ['featured', 'as seen in', 'press', 'media'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom',
      typicalScale: 'small',
    },
  },
  'trust-testimonial-quote': {
    id: 'trust-testimonial-quote',
    category: 'trust',
    label: 'Testimonial Quote Card',
    description: 'Pre-designed testimonial quote graphic',
    icon: 'MessageSquareQuote',
    examples: ['Customer quote card', '5-star review graphic'],
    usageContext: ['testimonial', 'review', 'social-proof'],
    requirements: {
      recommendedFormat: ['png', 'jpg'],
      transparentBackground: 'optional',
      minResolution: { width: 1080, height: 1080 },
      aspectRatio: 'square-preferred',
    },
    promptKeywords: ['testimonial', 'review', 'customer says'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'trust-rating-stars': {
    id: 'trust-rating-stars',
    category: 'trust',
    label: 'Rating/Stars Graphic',
    description: 'Star rating visualization (e.g., 4.8 stars)',
    icon: 'Star',
    examples: ['4.9 star rating graphic', 'Amazon rating badge'],
    usageContext: ['rating', 'reviews', 'social-proof'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 400, height: 100 },
      aspectRatio: 'landscape',
    },
    promptKeywords: ['rating', 'stars', 'reviews', 'rated'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom',
      typicalScale: 'small',
    },
  },
};

export const CREATIVE_ASSET_TYPES: Record<string, AssetType> = {
  'creative-background-texture': {
    id: 'creative-background-texture',
    category: 'creative',
    label: 'Background Texture/Pattern',
    description: 'Brand texture, pattern, or abstract background',
    icon: 'Palette',
    examples: ['Brand pattern', 'Textured background', 'Abstract brand art'],
    usageContext: ['background', 'motion-graphics', 'texture'],
    requirements: {
      recommendedFormat: ['jpg', 'png', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
      tileable: 'optional',
    },
    promptKeywords: ['background', 'texture', 'pattern'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'background',
      typicalScale: 'full',
    },
  },
  'creative-icon-set': {
    id: 'creative-icon-set',
    category: 'creative',
    label: 'Custom Icon Set',
    description: 'Brand-styled icons for infographics',
    icon: 'Shapes',
    examples: ['Ingredient icons', 'Benefit icons', 'Process step icons'],
    usageContext: ['infographic', 'icons', 'motion-graphics'],
    requirements: {
      recommendedFormat: ['svg', 'png'],
      transparentBackground: true,
      minResolution: { width: 200, height: 200 },
      aspectRatio: 'square',
    },
    promptKeywords: ['icon', 'graphic', 'symbol'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'flexible',
      typicalScale: 'small',
    },
  },
  'creative-illustration': {
    id: 'creative-illustration',
    category: 'creative',
    label: 'Custom Illustration',
    description: 'Brand illustration, artwork, or custom graphic',
    icon: 'PenTool',
    examples: ['Hand-drawn illustration', 'Brand artwork', 'Custom graphic'],
    usageContext: ['illustration', 'artistic', 'brand-story'],
    requirements: {
      recommendedFormat: ['png', 'svg', 'jpg'],
      transparentBackground: 'optional',
      minResolution: { width: 1000, height: 1000 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['illustration', 'artwork', 'graphic'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'flexible',
      typicalScale: 'medium-large',
    },
  },
  'creative-infographic': {
    id: 'creative-infographic',
    category: 'creative',
    label: 'Infographic/Data Viz',
    description: 'Pre-designed infographic or data visualization',
    icon: 'BarChart',
    examples: ['Ingredient comparison chart', 'Process infographic'],
    usageContext: ['education', 'data', 'comparison'],
    requirements: {
      recommendedFormat: ['png', 'svg', 'jpg'],
      transparentBackground: 'optional',
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['infographic', 'chart', 'data', 'comparison'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'creative-social-template': {
    id: 'creative-social-template',
    category: 'creative',
    label: 'Social Media Template',
    description: 'Pre-designed social post template',
    icon: 'Share2',
    examples: ['Instagram post template', 'Story template'],
    usageContext: ['social-media', 'template'],
    requirements: {
      recommendedFormat: ['png', 'psd', 'fig'],
      transparentBackground: false,
      minResolution: { width: 1080, height: 1080 },
      aspectRatio: 'platform-specific',
    },
    promptKeywords: [],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: false,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'creative-lower-third': {
    id: 'creative-lower-third',
    category: 'creative',
    label: 'Lower Third Template',
    description: 'Pre-designed lower third graphic for names/titles',
    icon: 'RectangleHorizontal',
    examples: ['Speaker name lower third', 'Title card template'],
    usageContext: ['lower-third', 'name-title', 'motion-graphics'],
    requirements: {
      recommendedFormat: ['png', 'svg'],
      transparentBackground: true,
      minResolution: { width: 1920, height: 300 },
      aspectRatio: 'wide',
    },
    promptKeywords: [],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'bottom',
      typicalScale: 'full-width',
    },
  },
  'creative-transition': {
    id: 'creative-transition',
    category: 'creative',
    label: 'Transition/Wipe',
    description: 'Pre-designed transition animation',
    icon: 'ArrowLeftRight',
    examples: ['Brand wipe transition', 'Logo reveal transition'],
    usageContext: ['transition', 'scene-change'],
    requirements: {
      recommendedFormat: ['mp4', 'webm', 'mov'],
      transparentBackground: 'recommended',
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9',
    },
    promptKeywords: [],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: false,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'creative-intro-video': {
    id: 'creative-intro-video',
    category: 'creative',
    label: 'Video Intro/Bumper',
    description: 'Pre-made video intro or bumper',
    icon: 'Film',
    examples: ['5-second logo intro', 'Brand bumper'],
    usageContext: ['intro', 'opener'],
    requirements: {
      recommendedFormat: ['mp4', 'mov'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9',
      maxDuration: 10,
    },
    promptKeywords: [],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: false,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'creative-outro-video': {
    id: 'creative-outro-video',
    category: 'creative',
    label: 'Video Outro/End Card',
    description: 'Pre-made video outro or end card',
    icon: 'Film',
    examples: ['End card with CTA', 'Closing animation'],
    usageContext: ['outro', 'closer', 'cta'],
    requirements: {
      recommendedFormat: ['mp4', 'mov'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9',
      maxDuration: 15,
    },
    promptKeywords: [],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: false,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'creative-music-audio': {
    id: 'creative-music-audio',
    category: 'creative',
    label: 'Brand Music/Jingle',
    description: 'Custom brand music, jingle, or audio signature',
    icon: 'Music',
    examples: ['Brand jingle', 'Sonic logo', 'Custom background music'],
    usageContext: ['audio', 'music', 'branding'],
    requirements: {
      recommendedFormat: ['mp3', 'wav', 'aac'],
      transparentBackground: false,
      minResolution: null,
      aspectRatio: 'n/a',
    },
    promptKeywords: [],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: false,
      typicalPosition: 'n/a',
      typicalScale: 'n/a',
    },
  },
};

export const SERVICES_ASSET_TYPES: Record<string, AssetType> = {
  'service-functional-health-hero': {
    id: 'service-functional-health-hero',
    category: 'services',
    label: 'Functional Health Services Hero',
    description: 'Main promotional image for Functional Health Services',
    icon: 'Activity',
    examples: ['Consultation room', 'Health assessment in progress'],
    usageContext: ['service-promotion', 'functional-health', 'hero'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['functional health', 'health services', 'consultation', 'assessment', 'holistic health'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'service-lab-testing-hero': {
    id: 'service-lab-testing-hero',
    category: 'services',
    label: 'Lab Testing Services Hero',
    description: 'Main promotional image for Lab Testing services',
    icon: 'FlaskConical',
    examples: ['Lab equipment', 'Test kits display', 'Sample collection'],
    usageContext: ['service-promotion', 'lab-testing', 'hero'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['lab testing', 'laboratory', 'test', 'analysis', 'diagnostic'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'service-bioscan-device': {
    id: 'service-bioscan-device',
    category: 'services',
    label: 'BioScan SRT Device',
    description: 'Photo of BioScan SRT equipment/device',
    icon: 'Cpu',
    examples: ['BioScan machine', 'SRT device close-up', 'Equipment in use'],
    usageContext: ['equipment', 'bioscan', 'technology'],
    requirements: {
      recommendedFormat: ['png', 'jpg'],
      transparentBackground: 'optional',
      minResolution: { width: 1200, height: 1200 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['BioScan', 'SRT', 'biofeedback', 'scanning', 'device', 'technology'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium-large',
    },
  },
  'service-weight-management-hero': {
    id: 'service-weight-management-hero',
    category: 'services',
    label: 'Weight Management Program Hero',
    description: 'Main promotional image for Weight Management program',
    icon: 'Scale',
    examples: ['Healthy lifestyle imagery', 'Fitness/nutrition combo', 'Transformation journey'],
    usageContext: ['program-promotion', 'weight-management', 'hero'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['weight management', 'weight loss', 'healthy weight', 'metabolism', 'body composition'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'service-hormone-health-hero': {
    id: 'service-hormone-health-hero',
    category: 'services',
    label: "Women's Hormone Health Hero",
    description: "Main promotional image for Women's Hormone Health program",
    icon: 'Heart',
    examples: ['Woman in wellness setting', 'Hormone balance imagery', 'Vitality/energy representation'],
    usageContext: ['program-promotion', 'hormone-health', 'hero'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['hormone health', "women's health", 'hormone balance', 'menopause', 'perimenopause', 'hormones'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'service-detox-hero': {
    id: 'service-detox-hero',
    category: 'services',
    label: 'Detoxification Program Hero',
    description: 'Main promotional image for Detoxification program',
    icon: 'Sparkles',
    examples: ['Cleanse/detox imagery', 'Renewal/fresh start', 'Clean eating'],
    usageContext: ['program-promotion', 'detox', 'hero'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['detox', 'detoxification', 'cleanse', 'purify', 'toxin', 'cleansing'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'service-stress-management-hero': {
    id: 'service-stress-management-hero',
    category: 'services',
    label: 'Stress Management Program Hero',
    description: 'Main promotional image for Stress Management program',
    icon: 'Brain',
    examples: ['Calm/relaxation imagery', 'Meditation', 'Peaceful setting'],
    usageContext: ['program-promotion', 'stress-management', 'hero'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['stress management', 'stress relief', 'relaxation', 'calm', 'anxiety', 'cortisol'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
  'service-consultation-room': {
    id: 'service-consultation-room',
    category: 'services',
    label: 'Consultation Room',
    description: 'Generic consultation or treatment room photo',
    icon: 'DoorOpen',
    examples: ['Client meeting room', 'Consultation space', 'Treatment area'],
    usageContext: ['location', 'services', 'consultation'],
    requirements: {
      recommendedFormat: ['jpg', 'webp'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['consultation', 'appointment', 'meeting', 'session'],
    placementRules: {
      canBeComposited: false,
      canBeAnimated: true,
      typicalPosition: 'full-frame',
      typicalScale: 'full',
    },
  },
};

export const DOCUMENT_ASSET_TYPES: Record<string, AssetType> = {
  'document-certificate': {
    id: 'document-certificate',
    category: 'documents',
    label: 'Certificate/License',
    description: 'Official certificate, license, or permit image',
    icon: 'FileCheck',
    examples: ['Business license', 'FDA registration', 'Organic certificate'],
    usageContext: ['compliance', 'credibility', 'legal'],
    requirements: {
      recommendedFormat: ['jpg', 'png', 'pdf'],
      transparentBackground: false,
      minResolution: { width: 1200, height: 900 },
      aspectRatio: 'document',
    },
    promptKeywords: ['certificate', 'license', 'certified', 'registered'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium',
    },
  },
  'document-lab-report': {
    id: 'document-lab-report',
    category: 'documents',
    label: 'Lab Report/COA',
    description: 'Certificate of Analysis or lab test results',
    icon: 'FileText',
    examples: ['Third-party lab report', 'Purity test results'],
    usageContext: ['testing', 'transparency', 'quality'],
    requirements: {
      recommendedFormat: ['jpg', 'png', 'pdf'],
      transparentBackground: false,
      minResolution: { width: 1200, height: 1600 },
      aspectRatio: 'document',
    },
    promptKeywords: ['lab report', 'test results', 'COA', 'analysis'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium',
    },
  },
  'document-screenshot-website': {
    id: 'document-screenshot-website',
    category: 'documents',
    label: 'Website Screenshot',
    description: 'Screenshot of company website or product page',
    icon: 'Monitor',
    examples: ['Homepage screenshot', 'Product page capture'],
    usageContext: ['website', 'digital', 'ecommerce'],
    requirements: {
      recommendedFormat: ['png', 'jpg'],
      transparentBackground: false,
      minResolution: { width: 1920, height: 1080 },
      aspectRatio: '16:9-preferred',
    },
    promptKeywords: ['website', 'online', 'shop', 'order'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium-large',
    },
  },
  'document-screenshot-app': {
    id: 'document-screenshot-app',
    category: 'documents',
    label: 'App Screenshot',
    description: 'Screenshot of mobile app or software',
    icon: 'Smartphone',
    examples: ['Mobile app screenshot', 'App store listing'],
    usageContext: ['app', 'mobile', 'digital'],
    requirements: {
      recommendedFormat: ['png', 'jpg'],
      transparentBackground: false,
      minResolution: { width: 1080, height: 1920 },
      aspectRatio: '9:16',
    },
    promptKeywords: ['app', 'mobile', 'download'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium',
    },
  },
  'document-screenshot-social': {
    id: 'document-screenshot-social',
    category: 'documents',
    label: 'Social Media Screenshot',
    description: 'Screenshot of social post, review, or comment',
    icon: 'MessageCircle',
    examples: ['Instagram post screenshot', 'Twitter mention'],
    usageContext: ['social-proof', 'ugc', 'reviews'],
    requirements: {
      recommendedFormat: ['png', 'jpg'],
      transparentBackground: false,
      minResolution: { width: 800, height: 800 },
      aspectRatio: 'flexible',
    },
    promptKeywords: ['social media', 'post', 'review', 'comment'],
    placementRules: {
      canBeComposited: true,
      canBeAnimated: true,
      typicalPosition: 'center',
      typicalScale: 'medium',
    },
  },
};

export const BRAND_ASSET_TYPES: Record<string, AssetType> = {
  ...PRODUCT_ASSET_TYPES,
  ...LOCATION_ASSET_TYPES,
  ...PEOPLE_ASSET_TYPES,
  ...LOGO_ASSET_TYPES,
  ...TRUST_ASSET_TYPES,
  ...CREATIVE_ASSET_TYPES,
  ...SERVICES_ASSET_TYPES,
  ...DOCUMENT_ASSET_TYPES,
};

export const ASSET_CATEGORIES: (AssetCategory & { types: AssetType[] })[] = [
  {
    id: 'products',
    label: 'Products',
    icon: 'Package',
    description: 'Product photos, packaging, ingredients',
    types: Object.values(PRODUCT_ASSET_TYPES),
  },
  {
    id: 'location',
    label: 'Location & Facility',
    icon: 'Building',
    description: 'Building, interior, grounds, manufacturing',
    types: Object.values(LOCATION_ASSET_TYPES),
  },
  {
    id: 'people',
    label: 'People',
    icon: 'Users',
    description: 'Founders, employees, customers, experts',
    types: Object.values(PEOPLE_ASSET_TYPES),
  },
  {
    id: 'logos',
    label: 'Logos & Branding',
    icon: 'Hexagon',
    description: 'Logos, wordmarks, watermarks',
    types: Object.values(LOGO_ASSET_TYPES),
  },
  {
    id: 'trust',
    label: 'Trust & Credibility',
    icon: 'ShieldCheck',
    description: 'Certifications, awards, partnerships, press',
    types: Object.values(TRUST_ASSET_TYPES),
  },
  {
    id: 'services',
    label: 'Services & Programs',
    icon: 'Activity',
    description: 'Functional health, lab testing, BioScan, wellness programs',
    types: Object.values(SERVICES_ASSET_TYPES),
  },
  {
    id: 'creative',
    label: 'Creative Assets',
    icon: 'Palette',
    description: 'Backgrounds, icons, templates, videos',
    types: Object.values(CREATIVE_ASSET_TYPES),
  },
  {
    id: 'documents',
    label: 'Documents & Screenshots',
    icon: 'FileText',
    description: 'Certificates, reports, screenshots',
    types: Object.values(DOCUMENT_ASSET_TYPES),
  },
];

export function getAssetType(typeId: string): AssetType | null {
  return BRAND_ASSET_TYPES[typeId] || null;
}

export const getAssetTypeById = getAssetType;

export function getTypesByCategory(categoryId: string): AssetType[] {
  return Object.values(BRAND_ASSET_TYPES).filter(t => t.category === categoryId);
}

export const getAssetTypesByCategory = getTypesByCategory;

export function findMatchingAssetTypes(prompt: string): string[] {
  const lower = prompt.toLowerCase();
  const matches: Array<{ typeId: string; score: number }> = [];
  
  for (const [typeId, assetType] of Object.entries(BRAND_ASSET_TYPES)) {
    let score = 0;
    
    for (const keyword of assetType.promptKeywords || []) {
      if (lower.includes(keyword.toLowerCase())) {
        score += 10;
      }
    }
    
    if (score > 0) {
      matches.push({ typeId, score });
    }
  }
  
  return matches
    .sort((a, b) => b.score - a.score)
    .map(m => m.typeId);
}
