import { Music, Volume2 } from 'lucide-react';
import { Switch } from '@/components/ui/switch';
import { getVisualStyleConfig } from '@shared/visual-style-config';

interface MusicStyleSelectorProps {
  enabled: boolean;
  onEnabledChange: (enabled: boolean) => void;
  visualStyle: string;
  customMood?: string;
  onMoodChange?: (mood: string) => void;
}

const MUSIC_MOODS = [
  { id: 'uplifting', name: 'Uplifting', description: 'Positive, inspiring' },
  { id: 'calm', name: 'Calm', description: 'Relaxing, peaceful' },
  { id: 'energetic', name: 'Energetic', description: 'Dynamic, exciting' },
  { id: 'emotional', name: 'Emotional', description: 'Heartfelt, moving' },
  { id: 'corporate', name: 'Corporate', description: 'Professional, confident' },
  { id: 'epic', name: 'Epic', description: 'Cinematic, powerful' },
];

export function MusicStyleSelector({
  enabled,
  onEnabledChange,
  visualStyle,
  customMood,
  onMoodChange,
}: MusicStyleSelectorProps) {
  const styleConfig = getVisualStyleConfig(visualStyle);
  const defaultMood = styleConfig.musicStyle.mood.split(',')[0].trim();
  const currentMood = customMood || defaultMood;

  return (
    <div className="space-y-3" data-testid="music-style-selector">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Music className="h-4 w-4 text-gray-500" />
          <span className="text-sm font-medium">Background Music</span>
        </div>
        <Switch 
          checked={enabled} 
          onCheckedChange={onEnabledChange}
          data-testid="switch-music-enabled"
        />
      </div>

      {enabled && (
        <div className="pl-6 space-y-3">
          <div className="flex items-center gap-2 text-xs text-gray-500">
            <Volume2 className="h-3 w-3" />
            <span data-testid="text-music-auto-match">
              Auto-matched to "{styleConfig.name}" style: {styleConfig.musicStyle.genre}
            </span>
          </div>

          <div>
            <label className="text-xs text-gray-500 mb-2 block">Music Mood</label>
            <div className="flex flex-wrap gap-2">
              {MUSIC_MOODS.map((mood) => (
                <button
                  key={mood.id}
                  type="button"
                  onClick={() => onMoodChange?.(mood.id)}
                  className={`
                    px-3 py-1.5 rounded-full text-xs transition-all
                    ${currentMood === mood.id
                      ? 'bg-primary text-white'
                      : 'bg-gray-100 text-gray-600 hover:bg-gray-200'}
                  `}
                  data-testid={`button-mood-${mood.id}`}
                >
                  {mood.name}
                </button>
              ))}
            </div>
          </div>

          <div className="bg-gray-50 rounded-lg p-3 text-xs" data-testid="music-preview-info">
            <p className="font-medium text-gray-700">Music Preview:</p>
            <p className="text-gray-500 mt-1">
              {styleConfig.musicStyle.genre} • {styleConfig.musicStyle.tempo} tempo • {styleConfig.musicStyle.energy} energy
            </p>
            <p className="text-gray-400 mt-1">
              Generated by Udio AI via PiAPI
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

export default MusicStyleSelector;
